//! lightwalletd gRPC client.
//!
//! lightwalletd is a server that speaks to a full Zcash node on our behalf.
//! Instead of downloading the entire blockchain (80+ GB), we ask lightwalletd
//! for compact blocks — stripped-down block summaries that contain just enough
//! data to detect incoming payments without revealing anything to the server.

// Pull in the Rust types generated by tonic-build from proto/service.proto.
pub mod proto {
    #![allow(dead_code)]
    tonic::include_proto!("cash.z.wallet.sdk.rpc");
}

use anyhow::Context;
use proto::{
    compact_tx_streamer_client::CompactTxStreamerClient, BlockId, BlockRange, ChainSpec,
    CompactBlock, TxFilter,
};
use tonic::transport::{Channel, ClientTlsConfig};

pub struct LightwalletdClient {
    inner: CompactTxStreamerClient<Channel>,
}

impl LightwalletdClient {
    /// Open a TLS-encrypted gRPC connection to a lightwalletd server.
    ///
    /// The URL comes from `LIGHTWALLETD_URL` in `.env`, e.g.
    /// `https://lightwalletd.testnet.electriccoin.co:9067`
    pub async fn connect(url: &str) -> anyhow::Result<Self> {
        let tls = ClientTlsConfig::new(); // tls-roots feature enables native root loading
        let channel = Channel::from_shared(url.to_owned())
            .context("invalid lightwalletd URL")?
            .tls_config(tls)
            .context("TLS config failed")?
            .connect()
            .await
            .context("could not connect to lightwalletd — is the URL correct and reachable?")?;

        Ok(Self {
            inner: CompactTxStreamerClient::new(channel),
        })
    }

    /// Return the current chain tip height.
    /// The worker uses this to know how far to scan.
    pub async fn get_latest_height(&mut self) -> anyhow::Result<u64> {
        let resp = self
            .inner
            .get_latest_block(ChainSpec {})
            .await
            .context("GetLatestBlock failed")?;
        Ok(resp.into_inner().height)
    }

    /// Fetch compact blocks in [start, end] (inclusive).
    ///
    /// Each compact block contains compact transaction records.  Each compact
    /// transaction contains compact Sapling outputs and Orchard actions — the
    /// minimum data needed to trial-decrypt and see if a note is ours.
    pub async fn get_block_range(
        &mut self,
        start: u64,
        end: u64,
    ) -> anyhow::Result<Vec<CompactBlock>> {
        let mut stream = self
            .inner
            .get_block_range(BlockRange {
                start: Some(BlockId { height: start, hash: vec![] }),
                end: Some(BlockId { height: end, hash: vec![] }),
            })
            .await
            .context("GetBlockRange failed")?
            .into_inner();

        let mut blocks = Vec::new();
        while let Some(block) = stream
            .message()
            .await
            .context("error reading block stream")?
        {
            blocks.push(block);
        }
        Ok(blocks)
    }

    /// Fetch the full raw transaction bytes for a given txid (hex string).
    ///
    /// Compact blocks only have 52-byte ciphertext — not enough for the memo.
    /// Once we detect a note is ours, we fetch the full transaction to read
    /// the complete 512-byte encrypted memo.
    pub async fn get_transaction(&mut self, txid_hex: &str) -> anyhow::Result<Vec<u8>> {
        let txid_bytes = hex::decode(txid_hex).context("invalid txid hex")?;

        let resp = self
            .inner
            .get_transaction(TxFilter {
                block: None,
                index: 0,
                hash: txid_bytes,
            })
            .await
            .context("GetTransaction failed")?;

        Ok(resp.into_inner().data)
    }
}
